/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlindBoxPopup: typeof import('./src/components/BlindBoxPopup.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    LocationPickerPopup: typeof import('./src/components/LocationPickerPopup.vue')['default']
    MatchConfirmModal: typeof import('./src/components/MatchConfirmModal.vue')['default']
    MatchIntroModal: typeof import('./src/components/MatchIntroModal.vue')['default']
    MatchSuccessModal: typeof import('./src/components/MatchSuccessModal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    TagSelector: typeof import('./src/components/TagSelector.vue')['default']
  }
}
